import type { FlowCopy } from '../../types.js';

export const p1Flows: FlowCopy[] = [
  {
    id: 'P1-01',
    title: 'Theo dõi phễu tuyển sinh',
    diagram: 'journey',
    whoStarts: 'Sale ghi nhận phụ huynh quan tâm',
    whoApproves: 'Không cần duyệt — cập nhật trạng thái cơ hội',
    systemDoes: 'Giữ lịch sử từng bước trên cùng một thẻ cơ hội',
    resultScreen: 'Bảng cơ hội CRM',
    milestones: [
      { title: 'Mới quan tâm' },
      { title: 'Đang tư vấn' },
      { title: 'Học thử / test' },
      { title: 'Chốt hoặc mất' },
    ],
    rules: ['Mọi cơ hội có dấu vết; đánh dấu mất phải kèm lý do'],
    sourceRef: 'docs/24-workflow-spec-p1.md · P1-01',
  },
  {
    id: 'P1-02',
    title: 'Lập phiếu học phí từ cơ hội',
    diagram: 'swimlane',
    whoStarts: 'Sale',
    whoApproves: 'Chưa duyệt ở bước này — phiếu ở trạng thái nháp',
    systemDoes: 'Gắn phiếu với cơ hội và số tiền đề xuất',
    resultScreen: 'Màn tạo phiếu thu',
    steps: [
      { actor: 'sale', action: 'Chọn cơ hội đã test' },
      { actor: 'sale', action: 'Lập phiếu thu nháp' },
      { actor: 'he_thong', action: 'Lưu nháp, chờ duyệt', system: true },
    ],
    rules: ['Phiếu nháp không kích hoạt học viên'],
    sourceRef: 'docs/24 · P1-02',
  },
  {
    id: 'P1-03',
    title: 'Duyệt phiếu kích hoạt học viên',
    diagram: 'control-gate',
    whoStarts: 'Sale đã lập phiếu nháp',
    whoApproves: 'Giám đốc Kinh doanh (thêm mắt khi vượt ngưỡng)',
    systemDoes: 'Ghi sổ thu; kích hoạt các bước phía sau',
    resultScreen: 'Hàng đợi phiếu thu / chi tiết phiếu',
    gateOptions: [
      { kind: 'approve', label: 'Duyệt', note: 'Tiền vào sổ' },
      { kind: 'return', label: 'Trả lại', note: 'Sai số / thiếu hồ sơ' },
      { kind: 'reject', label: 'Từ chối' },
      { kind: 'escalate', label: 'Cần mắt thứ hai', note: 'Vượt ngưỡng' },
    ],
    screenSketch: {
      title: 'Hàng đợi duyệt phiếu',
      regions: [
        { x: 2, y: 2, w: 96, h: 12, label: 'Phiếu thu — chờ duyệt', kind: 'header' },
        { x: 2, y: 18, w: 96, h: 55, label: 'Danh sách phiếu nháp', kind: 'table' },
        { x: 70, y: 78, w: 26, h: 14, label: 'Duyệt', kind: 'button' },
      ],
    },
    rules: ['Người lập và người duyệt phải khác nhau'],
    sourceRef: 'docs/24 · P1-03',
    notes: [
      'Luồng tiền quan trọng — nêu rõ tầng kiểm nghiệp vụ nếu có.',
      'Sale mở phiếu của mình sẽ không thấy nút duyệt.',
    ],
  },
  {
    id: 'P1-04',
    title: 'Tự sinh tài khoản khi thu tiền',
    diagram: 'before-after',
    whoStarts: 'Hệ thống — sau khi phiếu được duyệt',
    whoApproves: 'Không ai duyệt thêm',
    systemDoes: 'Tạo tài khoản phụ huynh và học sinh, mật khẩu mặc định',
    resultScreen: 'Không màn riêng — thấy khi đăng nhập lần đầu',
    before: {
      title: 'Nhập tay',
      items: ['Tạo user từng người', 'Dễ sai email', 'Trễ kích hoạt'],
    },
    after: {
      title: 'Tự động',
      items: ['Sinh ngay sau duyệt', 'Đổi mật khẩu lần đầu', 'Không ai gõ tay'],
    },
    sourceRef: 'docs/24 · P1-04',
  },
  {
    id: 'P1-05',
    title: 'Kích hoạt ghi danh khi đóng phí',
    diagram: 'swimlane',
    whoStarts: 'Duyệt phiếu thu',
    whoApproves: 'Giám đốc (ở bước phiếu); Sale xếp lớp thêm nếu cần',
    systemDoes: 'Mở ghi danh; cho phép xếp vào lớp',
    resultScreen: 'Quản lý học viên / xếp lớp',
    steps: [
      { actor: 'giam_doc_kinh_doanh', action: 'Duyệt phiếu' },
      { actor: 'he_thong', action: 'Kích hoạt ghi danh', system: true },
      { actor: 'sale', action: 'Xếp lớp (nếu cần lớp thứ hai)' },
    ],
    sourceRef: 'docs/24 · P1-05',
  },
  {
    id: 'P1-06',
    title: 'Liên kết phụ huynh và con',
    diagram: 'control-gate',
    whoStarts: 'Phụ huynh gửi yêu cầu liên kết',
    whoApproves: 'Nhân sự được phép trên màn quản lý phụ huynh',
    systemDoes: 'Gắn quan hệ sau khi duyệt — phụ huynh mới thấy dữ liệu con',
    resultScreen: 'Quản lý phụ huynh',
    gateOptions: [
      { kind: 'approve', label: 'Duyệt liên kết' },
      { kind: 'reject', label: 'Từ chối' },
    ],
    rules: ['Phụ huynh không tự duyệt yêu cầu của chính mình'],
    sourceRef: 'docs/24 · P1-06',
  },
  {
    id: 'P1-07',
    title: 'Phụ huynh đăng nhập xem con',
    diagram: 'journey',
    whoStarts: 'Phụ huynh',
    whoApproves: 'Không cần duyệt',
    systemDoes: 'Chỉ hiện dữ liệu các con đã liên kết',
    resultScreen: 'App phụ huynh',
    milestones: [
      { title: 'Đăng nhập' },
      { title: 'Chọn con' },
      { title: 'Xem lịch · điểm · bài' },
    ],
    sourceRef: 'docs/24 · P1-07',
  },
  {
    id: 'P1-08',
    title: 'Huỷ phiếu và hoàn tiền',
    diagram: 'control-gate',
    whoStarts: 'Giám đốc Kinh doanh',
    whoApproves: 'Chính GĐ Kinh doanh — thao tác có kiểm soát',
    systemDoes: 'Ghi vết huỷ/hoàn; không xoá lịch sử thu',
    resultScreen: 'Chi tiết phiếu thu',
    gateOptions: [
      { kind: 'reject', label: 'Huỷ phiếu', note: 'Kèm lý do' },
      { kind: 'return', label: 'Hoàn tiền', note: 'Sổ ghi điều chỉnh' },
    ],
    rules: ['Sổ ghi không sửa im lặng — mọi điều chỉnh để lại vết'],
    sourceRef: 'docs/24 · P1-08',
  },
  {
    id: 'P1-09',
    title: 'Giám sát bất thường tài chính',
    diagram: 'journey',
    whoStarts: 'Tác nhân tự động gợi ý bất thường',
    whoApproves: 'Giám đốc Đào tạo xem và xử lý',
    systemDoes: 'Phát hiện mẫu lạ, đưa vào hàng xem xét',
    resultScreen: 'Màn cảnh báo / hàng đợi liên quan',
    milestones: [
      { title: 'Phát hiện mẫu lạ' },
      { title: 'Đưa vào hàng xem xét' },
      { title: 'Người có thẩm quyền xử lý' },
    ],
    sourceRef: 'docs/24 · P1-09',
  },
];
