import type { FlowCopy } from '../../types.js';

export const p2Flows: FlowCopy[] = [
  {
    id: 'P2-01',
    title: 'Tạo lớp và sinh lịch buổi',
    diagram: 'swimlane',
    whoStarts: 'Giám đốc Đào tạo',
    whoApproves: 'Không cổng duyệt riêng — cấu hình lớp là thao tác quản trị',
    systemDoes: 'Tự sinh các buổi học theo lịch lặp',
    resultScreen: 'Quản lý lớp',
    steps: [
      { actor: 'giam_doc_dao_tao', action: 'Tạo lớp, chọn lịch' },
      { actor: 'he_thong', action: 'Sinh danh sách buổi', system: true },
    ],
    sourceRef: 'docs/26 · P2-01',
  },
  {
    id: 'P2-02',
    title: 'Điểm danh buổi học',
    diagram: 'journey',
    whoStarts: 'Giáo viên',
    whoApproves: 'Không cần duyệt',
    systemDoes: 'Lưu trạng thái có mặt; dùng cho công và báo phụ huynh',
    resultScreen: 'Màn buổi học / điểm danh',
    milestones: [
      { time: 'Đầu buổi', title: 'Mở điểm danh' },
      { title: 'Đánh dấu từng học sinh' },
      { title: 'Lưu — khóa buổi khi xong' },
    ],
    sourceRef: 'docs/26 · P2-02',
  },
  {
    id: 'P2-03',
    title: 'Mở bài tập theo tiến độ',
    diagram: 'journey',
    whoStarts: 'Học viên (khi tới mốc)',
    whoApproves: 'Không — theo cấu hình tiến độ lớp',
    systemDoes: 'Chỉ mở bài đúng giai đoạn, tránh làm trước/làm sai thứ tự',
    resultScreen: 'App học viên',
    milestones: [
      { title: 'Tới mốc tiến độ' },
      { title: 'Bài được mở' },
      { title: 'Học viên làm và nộp' },
    ],
    sourceRef: 'docs/26 · P2-03',
  },
  {
    id: 'P2-04',
    title: 'Cung cấp bài tập dạng tài liệu',
    diagram: 'swimlane',
    whoStarts: 'Giám đốc Đào tạo',
    whoApproves: 'Không cổng duyệt riêng',
    systemDoes: 'Gắn tài liệu vào lộ trình lớp',
    resultScreen: 'Quản lý nội dung / lớp',
    steps: [
      { actor: 'giam_doc_dao_tao', action: 'Tải hoặc chọn tài liệu bài' },
      { actor: 'he_thong', action: 'Hiển thị cho đúng lớp', system: true },
    ],
    sourceRef: 'docs/26 · P2-04',
  },
  {
    id: 'P2-05',
    title: 'Học viên làm bài và nộp',
    diagram: 'journey',
    whoStarts: 'Học viên',
    whoApproves: 'Không — chờ giáo viên chấm',
    systemDoes: 'Lưu bài nộp, chặn nộp trễ theo cấu hình',
    resultScreen: 'App học viên — bài tập',
    milestones: [
      { title: 'Mở bài' },
      { title: 'Làm trên tài liệu' },
      { title: 'Nộp' },
    ],
    sourceRef: 'docs/26 · P2-05',
  },
  {
    id: 'P2-06',
    title: 'Chấm bài và cộng sao',
    diagram: 'swimlane',
    whoStarts: 'Giáo viên',
    whoApproves: 'Không cổng duyệt thêm',
    systemDoes: 'Cộng sao vào số dư học sinh khi chấm xong',
    resultScreen: 'Màn chấm bài',
    steps: [
      { actor: 'giao_vien', action: 'Mở bài nộp' },
      { actor: 'giao_vien', action: 'Chấm điểm / nhận xét' },
      { actor: 'he_thong', action: 'Cộng sao', system: true },
    ],
    sourceRef: 'docs/26 · P2-06',
  },
  {
    id: 'P2-07',
    title: 'Nhận xét: AI soạn nháp, giáo viên chốt',
    diagram: 'swimlane',
    whoStarts: 'Hệ thống gợi ý nháp nhận xét',
    whoApproves: 'Giáo viên chốt trước khi phụ huynh thấy',
    systemDoes: 'Soạn nháp; không tự gửi khi chưa chốt',
    resultScreen: 'Màn nhận xét buổi / học sinh',
    steps: [
      { actor: 'agent', action: 'Soạn nháp nhận xét' },
      { actor: 'giao_vien', action: 'Sửa và chốt' },
      { actor: 'he_thong', action: 'Hiển thị cho phụ huynh', system: true },
    ],
    rules: ['AI không gửi thẳng — giáo viên là người chốt'],
    sourceRef: 'docs/26 · P2-07',
  },
  {
    id: 'P2-08',
    title: 'Gửi ảnh và tóm tắt buổi cho phụ huynh',
    diagram: 'journey',
    whoStarts: 'Giáo viên',
    whoApproves: 'Không cổng duyệt riêng',
    systemDoes: 'Đưa nội dung vào app phụ huynh đúng con',
    resultScreen: 'App phụ huynh · màn buổi học',
    milestones: [
      { title: 'Giáo viên tải ảnh / tóm tắt' },
      { title: 'Hệ thống gửi đúng phụ huynh' },
      { title: 'Phụ huynh xem trên app' },
    ],
    sourceRef: 'docs/26 · P2-08',
  },
];
