import type { FlowCopy } from '../../types.js';

export const p3Flows: FlowCopy[] = [
  {
    id: 'P3-01',
    title: 'Chấm công vào/ra mỗi ngày',
    diagram: 'journey',
    whoStarts: 'Nhân sự (Sale, giáo viên, …)',
    whoApproves: 'Không — chấm trong mạng cho phép là hợp lệ',
    systemDoes: 'Ghi cặp vào/ra; dùng cho tính công cuối tháng',
    resultScreen: 'Màn chấm công',
    milestones: [
      { time: 'Sáng', title: 'Chấm vào' },
      { time: 'Chiều', title: 'Chấm ra' },
      { title: 'Hệ thống ghép ca trong ngày' },
    ],
    rules: ['Chấm ngoài mạng cho phép đi đường offsite'],
    sourceRef: 'docs/27 · P3-01',
  },
  {
    id: 'P3-02',
    title: 'Duyệt chấm công ngoài cơ sở',
    diagram: 'control-gate',
    whoStarts: 'Nhân sự chấm ngoài mạng cho phép',
    whoApproves: 'Giám đốc Kinh doanh hoặc Giám đốc Đào tạo',
    systemDoes: 'Giữ bản ghi chờ duyệt; chỉ tính công khi được chấp nhận',
    resultScreen: 'Hàng đợi chấm công offsite',
    gateOptions: [
      { kind: 'approve', label: 'Duyệt công ngoài' },
      { kind: 'reject', label: 'Từ chối' },
    ],
    sourceRef: 'docs/27 · P3-02',
  },
  {
    id: 'P3-03',
    title: 'Đăng ký ca làm',
    diagram: 'journey',
    whoStarts: 'Sale hoặc giáo viên',
    whoApproves: 'Chưa — đăng ký ở trạng thái chờ',
    systemDoes: 'Ghi nguyện vọng ca, chờ người có thẩm quyền',
    resultScreen: 'Màn đăng ký ca',
    milestones: [
      { title: 'Chọn khung ca' },
      { title: 'Gửi đăng ký' },
      { title: 'Chờ duyệt' },
    ],
    sourceRef: 'docs/27 · P3-03',
  },
  {
    id: 'P3-04',
    title: 'Duyệt ca làm',
    diagram: 'control-gate',
    whoStarts: 'Nhân sự đã đăng ký ca',
    whoApproves: 'Giám đốc Kinh doanh / Giám đốc Đào tạo',
    systemDoes: 'Khóa ca đã duyệt vào lịch vận hành',
    resultScreen: 'Hàng đợi duyệt ca',
    gateOptions: [
      { kind: 'approve', label: 'Duyệt ca' },
      { kind: 'reject', label: 'Từ chối', note: 'Có thể kèm lý do (xem P3-07)' },
    ],
    sourceRef: 'docs/27 · P3-04',
  },
  {
    id: 'P3-05',
    title: 'Chốt lương tháng theo bậc',
    diagram: 'swimlane',
    whoStarts: 'Giám đốc có thẩm quyền chốt',
    whoApproves: 'Chốt lương là cổng cuối của tháng',
    systemDoes: 'Tính theo bậc, công, KPI đã chốt',
    resultScreen: 'Màn chốt lương',
    steps: [
      { actor: 'he_thong', action: 'Tổng hợp công · ca · KPI', system: true },
      { actor: 'giam_doc_kinh_doanh', action: 'Rà và chốt tháng' },
      { actor: 'he_thong', action: 'Khóa bảng lương', system: true },
    ],
    rules: ['Chốt xong không sửa im lặng'],
    sourceRef: 'docs/27 · P3-05',
    notes: ['Luồng tiền/lương — nêu tầng kiểm số nếu ban giám đốc hỏi.'],
  },
  {
    id: 'P3-06',
    title: 'Nộp và duyệt phiếu KPI',
    diagram: 'control-gate',
    whoStarts: 'Sale hoặc giáo viên nộp phiếu',
    whoApproves: 'Giám đốc phụ trách',
    systemDoes: 'Gợi ý điểm theo quy tắc; người duyệt vẫn chốt',
    resultScreen: 'Màn KPI',
    gateOptions: [
      { kind: 'approve', label: 'Duyệt điểm' },
      { kind: 'return', label: 'Trả lại bổ sung' },
      { kind: 'reject', label: 'Không chấp nhận' },
    ],
    rules: ['Điểm gợi ý không thay người duyệt'],
    sourceRef: 'docs/27 · P3-06',
  },
  {
    id: 'P3-07',
    title: 'Từ chối đăng ký ca kèm lý do',
    diagram: 'control-gate',
    whoStarts: 'Người duyệt ca',
    whoApproves: 'Chính thao tác từ chối',
    systemDoes: 'Ghi lý do; người đăng ký thấy được',
    resultScreen: 'Hàng đợi duyệt ca',
    gateOptions: [
      { kind: 'reject', label: 'Từ chối', note: 'Bắt buộc lý do' },
    ],
    sourceRef: 'docs/27 · P3-07',
  },
  {
    id: 'P3-08',
    title: 'Tất toán KPI theo cơ sở',
    diagram: 'swimlane',
    whoStarts: 'Giám đốc phụ trách cơ sở',
    whoApproves: 'Thao tác tất toán là chốt phạm vi cơ sở',
    systemDoes: 'Khóa điểm KPI đã duyệt trong kỳ của cơ sở đó',
    resultScreen: 'Màn tất toán KPI',
    steps: [
      { actor: 'giam_doc_dao_tao', action: 'Chọn kỳ và cơ sở' },
      { actor: 'giam_doc_dao_tao', action: 'Tất toán' },
      { actor: 'he_thong', action: 'Khóa điểm đã chốt', system: true },
    ],
    rules: ['Mỗi cơ sở chỉ tất toán dữ liệu của mình'],
    sourceRef: 'docs/27 · P3-08',
  },
  {
    id: 'P3-09',
    title: 'Tính lại điểm KPI tự động',
    diagram: 'before-after',
    whoStarts: 'Người có quyền yêu cầu tính lại, hoặc sự kiện dữ liệu đổi',
    whoApproves: 'Không thay cổng duyệt người — chỉ làm mới điểm gợi ý',
    systemDoes: 'Tính lại điểm theo quy tắc hiện hành',
    resultScreen: 'Màn KPI',
    before: {
      title: 'Trước tính lại',
      items: ['Điểm cũ theo dữ liệu cũ'],
    },
    after: {
      title: 'Sau tính lại',
      items: ['Điểm gợi ý mới', 'Vẫn cần người duyệt nếu chưa chốt'],
    },
    sourceRef: 'docs/27 · P3-09',
  },
  {
    id: 'P3-10',
    title: 'Đánh giá buổi học đã hoàn thành',
    diagram: 'swimlane',
    whoStarts: 'Hệ thống (chạy nền)',
    whoApproves: 'Không giao diện người — job nội bộ',
    systemDoes: 'Đánh dấu buổi đủ điều kiện hoàn thành để tính công/lịch',
    resultScreen: 'Không màn người dùng — thấy gián tiếp trên lịch/công',
    steps: [
      { actor: 'he_thong', action: 'Quét buổi đủ điều kiện', system: true },
      { actor: 'he_thong', action: 'Đánh dấu hoàn thành', system: true },
    ],
    rules: ['Luồng nền — không có nút bấm trên UI'],
    sourceRef: 'docs/27 · P3-10',
  },
  {
    id: 'P3-11',
    title: 'Tự huỷ buổi không điểm danh và xếp bù',
    diagram: 'swimlane',
    whoStarts: 'Hệ thống (chạy nền)',
    whoApproves: 'Không — theo quy tắc thời hạn',
    systemDoes: 'Huỷ buổi 0 điểm danh; gợi ý/xếp buổi bù theo cấu hình',
    resultScreen: 'Không màn riêng — thấy trên lịch lớp',
    steps: [
      { actor: 'he_thong', action: 'Phát hiện buổi không điểm danh', system: true },
      { actor: 'he_thong', action: 'Huỷ và xử lý bù', system: true },
    ],
    sourceRef: 'docs/27 · P3-11',
  },
];
