// reconciliation router — P5: finance audit flag review surface.
//
// Flags are generated by the reconcile-finance-flags worker (ai:recon actor).
// Staff with reconciliation.review (GĐKD / GĐĐT / super_admin) can list,
// dismiss, or action flags. Every state transition writes an AuditLog.
//
// Status lifecycle: open → dismissed | actioned (terminal — no re-open).

import { z } from 'zod';
import { withFacility } from '@cmc/db';
import { notFound, badRequest } from '../errors.js';
import { requirePermission, router, scoped } from '../trpc.js';

const listFlagsInput = z.object({
  kind: z
    .enum(['self_approved', 'exceeds_threshold', 'excess_refunds', 'missing_provisioning'])
    .optional(),
});

const flagActionInput = z.object({
  flagId: z.string().uuid(),
});

export const reconciliationRouter = router({
  /**
   * Lists open ReconciliationFlags for the caller's facility.
   * Optional `kind` filter narrows to one rule type.
   */
  listFlags: requirePermission('reconciliation', 'review')
    .input(listFlagsInput)
    .query(async ({ ctx, input }) => {
      const { facilityId } = scoped(ctx);
      return withFacility(ctx.db, facilityId, (tx) =>
        tx.reconciliationFlag.findMany({
          where: {
            facilityId,
            status: 'open',
            ...(input.kind ? { kind: input.kind } : {}),
          },
          orderBy: { createdAt: 'asc' },
        }),
      );
    }),

  /**
   * Dismiss a flag: open → dismissed.
   * Records the resolving staff member and creates an AuditLog entry.
   */
  dismiss: requirePermission('reconciliation', 'review')
    .input(flagActionInput)
    .mutation(async ({ ctx, input }) => {
      const { facilityId } = scoped(ctx);
      const actor = ctx.subject!.userId;

      return withFacility(ctx.db, facilityId, async (tx) => {
        const flag = await tx.reconciliationFlag.findFirst({
          where: { id: input.flagId, facilityId },
        });
        if (!flag) throw notFound('Reconciliation flag not found.');
        if (flag.status !== 'open') {
          throw badRequest(`Flag is already ${flag.status}; only open flags can be dismissed.`);
        }

        const updated = await tx.reconciliationFlag.update({
          where: { id: input.flagId },
          data: {
            status: 'dismissed',
            resolvedById: actor,
            resolvedAt: new Date(),
          },
        });

        await tx.auditLog.create({
          data: {
            actor,
            action: 'reconciliation.dismiss',
            entity: 'ReconciliationFlag',
            entityId: flag.id,
            data: { kind: flag.kind, receiptId: flag.receiptId },
          },
        });

        return updated;
      });
    }),

  /**
   * Action a flag: open → actioned.
   * Indicates the staff member acted on the underlying issue.
   * Records the resolving staff member and creates an AuditLog entry.
   */
  action: requirePermission('reconciliation', 'review')
    .input(flagActionInput)
    .mutation(async ({ ctx, input }) => {
      const { facilityId } = scoped(ctx);
      const actor = ctx.subject!.userId;

      return withFacility(ctx.db, facilityId, async (tx) => {
        const flag = await tx.reconciliationFlag.findFirst({
          where: { id: input.flagId, facilityId },
        });
        if (!flag) throw notFound('Reconciliation flag not found.');
        if (flag.status !== 'open') {
          throw badRequest(`Flag is already ${flag.status}; only open flags can be actioned.`);
        }

        const updated = await tx.reconciliationFlag.update({
          where: { id: input.flagId },
          data: {
            status: 'actioned',
            resolvedById: actor,
            resolvedAt: new Date(),
          },
        });

        await tx.auditLog.create({
          data: {
            actor,
            action: 'reconciliation.action',
            entity: 'ReconciliationFlag',
            entityId: flag.id,
            data: { kind: flag.kind, receiptId: flag.receiptId },
          },
        });

        return updated;
      });
    }),
});
